spring.application.name=prj22-esercitazione-cinema

server.port=9001

#DB
spring.datasource.url=jdbc:mysql://localhost/prj22
spring.datasource.username=root
spring.datasource.password=root

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
