spring.application.name=Prj15_Bar

server.port=9001

#hibernate
spring.datasource.url=jdbc:mysql://localhost:3306/bar
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.defer-datasource-initialization=true