spring.application.name=Prj17_NegozioOrtofrutta_Spring

server.port = 9017

spring.datasource.url=jdbc:mysql://localhost:3306/prj17
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true