spring.application.name=magazzino

server.port=9003

# DB
#spring.datasource.url=jdbc:h2:file:./db/magazzino;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
#spring.datasource.username=sa
#spring.datasource.password=
#pring.datasource.driver-class-name=org.h2.Driver
#spring.h2.console.enabled=true
#spring.h2.console.path=/console
#
## JPA/HIBERNATE
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## LOGGING
#logging.level.org.springframework=INFO
#logging.level.com.querio=DEBUG

# CORS
#spring.web.cors.allowed-origins=*


spring.datasource.url=jdbc:h2:file:./data/dbdemo
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/console

#mettere su always al primo avvio
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update